Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: thalesburakowski-try
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred